USE [master]
GO

/****** Object:  Database [RES]    Script Date: 2022/01/05 15:34:16 ******/
CREATE DATABASE [RES]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RES', FILENAME = N'C:\Users\pales\RES.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RES_log', FILENAME = N'C:\Users\pales\RES_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RES] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RES] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RES] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RES] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RES] SET ARITHABORT OFF 
GO

ALTER DATABASE [RES] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RES] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RES] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RES] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RES] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RES] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RES] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RES] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RES] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RES] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RES] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RES] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RES] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RES] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RES] SET  MULTI_USER 
GO

ALTER DATABASE [RES] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RES] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RES] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RES] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RES] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RES] SET QUERY_STORE = OFF
GO

USE [RES]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [RES] SET  READ_WRITE 
GO


